#ifndef WINC1500_REGISTERS_H
#define WINC1500_REGISTERS_H

// Register Definitions from host_drv_19_3_0
#define NMI_PERIPH_REG_BASE     0x1000
#define NMI_INTR_REG_BASE       (NMI_PERIPH_REG_BASE + 0xa00)
#define CHIPID                  NMI_PERIPH_REG_BASE
#define NMI_INTR_ENABLE         NMI_INTR_REG_BASE
#define NMI_PIN_MUX_0           (NMI_PERIPH_REG_BASE + 0x408)
#define NMI_GLB_RESET_0			(NMI_PERIPH_REG_BASE + 0x400)
#define NMI_STATE_REG			(0x108c)
#define NMI_REV_REG  			(0x207ac)
#define NMI_REV_REG_ATE			(0x1048)

#define rNMI_GP_REG_0			(0x149c)
#define rNMI_GP_REG_1			(0x14A0)
#define rNMI_GP_REG_2			(0xc0008)
#define rNMI_BOOT_RESET_MUX		(0x1118)
#define BOOTROM_REG				(0xc000c)

#define WIFI_HOST_RCV_CTRL_0	(0x1070)
#define WIFI_HOST_RCV_CTRL_1	(0x1084)
#define WIFI_HOST_RCV_CTRL_2    (0x1078)
#define WIFI_HOST_RCV_CTRL_3    (0x106c)
#define WAKE_REG				(0x1074)

#define M2M_WAIT_FOR_HOST_REG 	(0x207bc)

#define NMI_SPI_REG_BASE        0xE800
#define NMI_SPI_CTL             (NMI_SPI_REG_BASE)
#define NMI_SPI_MASTER_DMA_ADDR (NMI_SPI_REG_BASE+0x4)
#define NMI_SPI_MASTER_DMA_COUNT (NMI_SPI_REG_BASE+0x8)
#define NMI_SPI_SLAVE_DMA_ADDR  (NMI_SPI_REG_BASE+0xc)
#define NMI_SPI_SLAVE_DMA_COUNT (NMI_SPI_REG_BASE+0x10)
#define NMI_SPI_TX_MODE         (NMI_SPI_REG_BASE+0x20)
#define NMI_SPI_PROTOCOL_CONFIG (NMI_SPI_REG_BASE+0x24) // Bits 2 and 3 control CRC
#define NMI_SPI_INTR_CTL        (NMI_SPI_REG_BASE+0x2c)

#define SPI_FLASH_BASE			(0x10200)
#define SPI_FLASH_MODE			(SPI_FLASH_BASE + 0x00)
#define SPI_FLASH_CMD_CNT		(SPI_FLASH_BASE + 0x04)
#define SPI_FLASH_DATA_CNT		(SPI_FLASH_BASE + 0x08)
#define SPI_FLASH_BUF1			(SPI_FLASH_BASE + 0x0c)
#define SPI_FLASH_BUF2			(SPI_FLASH_BASE + 0x10)
#define SPI_FLASH_BUF_DIR		(SPI_FLASH_BASE + 0x14)
#define SPI_FLASH_TR_DONE		(SPI_FLASH_BASE + 0x18)
#define SPI_FLASH_DMA_ADDR		(SPI_FLASH_BASE + 0x1c)
#define SPI_FLASH_MSB_CTL		(SPI_FLASH_BASE + 0x20)
#define SPI_FLASH_TX_CTL		(SPI_FLASH_BASE + 0x24)

#endif // WINC1500_REGISTERS_H
