#define CONF_WINC_USE_SPI
#define NM_EDGE_INTERRUPT   (1)
//#define NM_LEVEL_INTERRUPT  (0)

#define CONF_WINC_PIN_CHIP_ENABLE 20
#define CONF_WINC_PIN_RESET 21
#define CONF_WINC_PIN_WAKE 22

#define CONF_WINC_SPI_PORT spi0
#define CONF_WINC_SPI_CS_PIN 17
#define CONF_WINC_SPI_MISO_PIN 16
#define CONF_WINC_SPI_MOSI_PIN 19
#define CONF_WINC_SPI_SCK_PIN 18
#define CONF_WINC_SPI_INT_PIN 22