#define CONF_WINC_USE_SPI
#define NM_EDGE_INTERRUPT   (1)
//#define NM_LEVEL_INTERRUPT  (0)

#define CONF_WINC_PIN_CHIP_ENABLE 7
#define CONF_WINC_PIN_RESET 6
#define CONF_WINC_PIN_WAKE 8

#define CONF_WINC_SPI_PORT spi1
#define CONF_WINC_SPI_CS_PIN 13
#define CONF_WINC_SPI_MISO_PIN 12
#define CONF_WINC_SPI_MOSI_PIN 11
#define CONF_WINC_SPI_SCK_PIN 10
#define CONF_WINC_SPI_INT_PIN 9